<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class SuperAdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create super_admin role if it doesn't exist
        $superAdminRole = Role::firstOrCreate(['name' => 'super_admin']);

        // Get all permissions from the database (generated by Shield)
        $permissions = Permission::all()->pluck('name')->toArray();

        // Create all permissions
        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // Assign all permissions to super_admin role
        $superAdminRole->syncPermissions($permissions);

        // Create super admin user if it doesn't exist
        $superAdminUser = User::firstOrCreate(
            ['email' => 'karl@socotec.com'],
            [
                'name' => 'Super Admin',
                'password' => Hash::make('topsx49ZX'),
                'email_verified_at' => now(),
            ]
        );

        // Assign super_admin role to the user
        $superAdminUser->assignRole('super_admin');

        $this->command->info('Super Admin role created with all permissions!');
        $this->command->info('Super Admin user created: karl@socotec.com / topsx49ZX');
    }
}
